package app.tilt.marvel.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFBB161F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD6)
val md_theme_light_onPrimaryContainer = Color(0xFF410003)
val md_theme_light_secondary = Color(0xFF0161A3)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001D36)
val md_theme_light_tertiary = Color(0xFF9C404C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDADB)
val md_theme_light_onTertiaryContainer = Color(0xFF40000E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF6FEFF)
val md_theme_light_onBackground = Color(0xFF001F24)
val md_theme_light_surface = Color(0xFFF6FEFF)
val md_theme_light_onSurface = Color(0xFF001F24)
val md_theme_light_surfaceVariant = Color(0xFFF5DDDB)
val md_theme_light_onSurfaceVariant = Color(0xFF534342)
val md_theme_light_outline = Color(0xFF857371)
val md_theme_light_inverseOnSurface = Color(0xFFD0F8FF)
val md_theme_light_inverseSurface = Color(0xFF00363D)
val md_theme_light_inversePrimary = Color(0xFFFFB3AD)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFBB161F)

val md_theme_dark_primary = Color(0xFFFFB3AD)
val md_theme_dark_onPrimary = Color(0xFF680008)
val md_theme_dark_primaryContainer = Color(0xFF930010)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_secondary = Color(0xFF9ECAFF)
val md_theme_dark_onSecondary = Color(0xFF003258)
val md_theme_dark_secondaryContainer = Color(0xFF00497D)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_tertiary = Color(0xFFFFB2B8)
val md_theme_dark_onTertiary = Color(0xFF5F1220)
val md_theme_dark_tertiaryContainer = Color(0xFF7D2935)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDADB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F24)
val md_theme_dark_onBackground = Color(0xFF97F0FF)
val md_theme_dark_surface = Color(0xFF001F24)
val md_theme_dark_onSurface = Color(0xFF97F0FF)
val md_theme_dark_surfaceVariant = Color(0xFF534342)
val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BF)
val md_theme_dark_outline = Color(0xFFA08C8A)
val md_theme_dark_inverseOnSurface = Color(0xFF001F24)
val md_theme_dark_inverseSurface = Color(0xFF97F0FF)
val md_theme_dark_inversePrimary = Color(0xFFBB161F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB3AD)


val seed = Color(0xFFE23636)
