name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Update Username from Secrets
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: echo API_KEY="$API_KEY" > ./local.properties
    - name: Run Android Check
      run: ./gradlew check
